window_padding_width 32
font_size 14.0
background #0D0800
foreground #FFB300
cursor #FFB300
selection_background #FF6F00
selection_foreground #0D0800
adjust_line_height 150%

color0 #0D0800
color1 #FF3D00
color2 #FFB300
color3 #FF6F00
color4 #FFA000
color5 #FF8F00
color6 #FFE082
color7 #FFF8E1
color8 #3A2A00
color9 #FF6E40
color10 #FFD740
color11 #FFAB40
color12 #FFD180
color13 #FFAB00
color14 #FFE57F
color15 #FFFFF0

font_family monospace
